// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8d7d7f67-43fe-453a-9e64-f0cc831fe728";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onServo1ControlChange();
void onServo2ControlChange();
extern bool servo1Status;
extern bool servo2Status;


float pressureCloud;
float temperatureCloud;
int mq135ValueCloud;
bool servo1Control;
bool servo2Control;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(pressureCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatureCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mq135ValueCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(servo1Control, READWRITE, ON_CHANGE, onServo1ControlChange);
  ArduinoCloud.addProperty(servo2Control, READWRITE, ON_CHANGE, onServo2ControlChange);
  ArduinoCloud.addProperty(servo1Status, READ, ON_CHANGE, NULL);
ArduinoCloud.addProperty(servo2Status, READ, ON_CHANGE, NULL);


}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
